package com.example.fleet_backend.model;

public enum PostMissionDecision {
    ASSIGN_NEXT_MISSION_SAME_DRIVER,
    ASSIGN_NEXT_MISSION_OTHER_DRIVER,
    WAIT_ON_FIELD,
    RETURN_TO_DEPOT,
    MAINTENANCE_REQUIRED,
    LIGHT_BREAKDOWN_RETURN,
    TOW_REQUIRED,
    END_OF_SHIFT_RETURN,
    REST_REQUIRED,
    REFUEL_REQUIRED,
    INSPECTION_REQUIRED,
    SLEEP_OUTSIDE_DEPOT,
    REGIONAL_STAY,
    RETURN_DEPOT_AFTER_CANCELLED_NEXT_MISSION
}